In [1]:
import numpy as np 
import matplotlib.pyplot as plt
from matplotlib import style

In [2]:
def prdict(x,w,b):
    m = len(x)
    result = np.zeros(m)
    for i in range(m):
        result[i] = w*x[i]+b
    return result

In [3]:
def cost_function(x, y, w, b):
    result =prdict(x,w,b)
    cost = ((result-y)**2).sum()
    return (cost/(2*len(x)))
    

In [4]:
def gradient_descent(x,y,w,b):
    m = len(x)
    grad_w = 0
    grad_b = 0
    for i in range(m):
        predict = x[i]*w+b
        grad_w += (predict-y[i])*x[i]
        grad_b += (predict-y[i])
        
    return grad_w/m,grad_b/m
    

In [5]:
x_train = np.array([1.0, 2.0,3.0])
y_train = np.array([300.0, 500.0,700])

In [6]:
w = 0
b = 0
alpha = .001
for i in range(10000):
    grad_w,grad_b = gradient_descent(x_train,y_train,w,b)
    w = w - alpha*grad_w
    b = b - alpha*grad_b
    if i % 1000 == 0:
        temp_f_wb = prdict(x_train,w,b)
        print(temp_f_wb)



[1.63333333 2.76666667 3.9       ]
[293.874324   497.0213095  700.16829499]
[295.56093105 499.04098732 702.5210436 ]
[296.06751511 499.15606787 702.24462062]
[296.51292415 499.25167669 701.99042924]
[296.90787143 499.3364321  701.76499278]
[297.25808682 499.411588   701.56508918]
[297.5686367  499.47823171 701.38782672]
[297.84401362 499.53732734 701.23064106]
[298.08820127 499.58972978 701.0912583 ]
